### ISSUE TITLE
Metric vertx_net_client_active_connections not being decreased

### ISSUE THREAD

**Issue by Mersenne255** [vert-x3/vertx-micrometer-metrics#131]
### Version

vertx 4.2.0

### Context

Values for gauge metric `vertx_net_client_active_connections` are not being decreased on http connection closed.

### Do you have a reproducer?

https://github.com/Mersenne255/vertx_issue_4185_reproducer
Reproducer submits single http request and ends afterwards.
`vertx_net_client_active_connections` keeps showing value of 1, http metric vertx_http_client_active_connections is correctly decreased to 0.

### Extra

JVM 17.0.1

**Comment by jotak** [comment]
Hi @Mersenne255 ,

There's indeed an issue with the active connections for net client, whereas the active connections for the HTTP client is correct (we can see that in your reproducer). If you're only interested in tracking the HTTP active connections, I'd suggest that you just ignore the net client metric until we can fix it.

@vietj if I'm correct the issue with the net client is because the HTTP client uses the Net Client to establish the connection (hence increments the gauge) but it doesn't seem to use that same client/code while disconnecting. Remember the discussion that we had here: https://github.com/vert-x3/vertx-micrometer-metrics/pull/123#issuecomment-854094628 ? It seems to be the same problem here. So I think it's something to fix in the net client or the http client : either to have the HTTP client calling net client's metrics "disconnected" hook, or have the net client not calling metrics connection/disconnection hooks when used from the HTTP client.

**Comment by vietj** [comment]
it seems lke a bug in vertx core

**Comment by vietj** [comment]
i will take care of it

**Comment by vietj** [comment]
I'm also have a look now :-)
