### ISSUE TITLE
Performance analysis and improvements

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-micrometer-metrics#184]
- Performance analysis on typical use case
- Measure overhead (GC, CPU, throughput, latency)
- Compare overhead to other implementations (Quarkus, Spring)
- Make changes for new target
- Possible breaking API and metric names changes
- Evaluate limitations due to Micrometer implementation

**Comment by tsegismont** [comment]
Comparison of throughput using Techempower benchmark Vert.x core implementation

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/9f3380f1-4323-4233-a807-37e46aca2fb7)

Up to 64% reduced throughput when Micrometer Metrics is enabled.

CPU profiling shows a lot of time is spent on reporting metrics:

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/73d8a6f8-7e37-4350-9740-28bdcd83d6d1)

Digging a little deeper, dynamic resolution of the meters is actually the problem:

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/0df3de26-fd8b-41ac-a3e7-230440bcfe0c)

You can see this by the calls to the following methods:

- `io.vertx.micrometer.impl.meters.Counters#get(java.lang.Iterable<io.micrometer.core.instrument.Tag>, java.lang.String...)`
- `io.vertx.micrometer.impl.meters.Gauges#get(java.lang.Iterable<io.micrometer.core.instrument.Tag>, java.lang.String...)`
- ...

**Comment by tsegismont** [comment]
Comparison of throughput using Techempower fortunes benchmark (Vert.x core implementation)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/2bceee00-af11-4125-aeaa-f0973fbcd85d)

CPU profiling, with metrics related frames in fuchsia (Vert.x + Micrometer)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/354aa5d4-2410-4543-814a-46c6f58fc082)


Up to 10% reduced throughput when Micrometer Metrics is enabled.

**Comment by tsegismont** [comment]
With the following changes:

- Avoid meters lookup where possible  21d9f758c03704951bc672b57278bfd1340a0cba
- Filter tags up front instead of using a Micrometer meter filter a4e266b9365e1e1c6d5e4d8cad2d0691a9d374b6
- Do not compute metric name on the hot path c04d001eb1b84a4678e72828b473b00a709db69c
- Avoid redundant copies when combining tags 33f060f85e2e4ef0e5f0853037928fa0d53bd9b8

Comparison of throughput using Techempower plaintext benchmark (Vert.x core implementation)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/ab75b003-40bb-40f4-a53c-dc3dcb7a1345)

Throughput improved by 36% 

Comparison of throughput using Techempower fortunes benchmark (Vert.x core implementation)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/1a088a90-1450-4d89-b21e-d22c689df972)

Throughput improved by 5%

**Comment by tsegismont** [comment]
With the following additional change:

- Use a per-thread meter cache before looking up for meters in the registry  2af287b

⚠️ **THIS CHANGE IMPLIES MICROMETER FILTERS ARE NOT UPDATED AFTER INITIAL CONFIG** ⚠️

Comparison of throughput using Techempower plaintext benchmark (Vert.x core implementation)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/a5ff8c2b-67b4-4865-b927-9e7c4cf2fcb7)

Throughput improved by 61% 

Comparison of throughput using Techempower fortunes benchmark (Vert.x core implementation)

![image](https://github.com/vert-x3/vertx-micrometer-metrics/assets/1500598/a9cbb344-c681-48b3-b1b5-12306fafbe9a)

Throughput improved by 8% 

We could have this cache disabled by default and let users know they must not update Micrometer config if it's enabled

If Micrometer can be updated as described in https://github.com/micrometer-metrics/micrometer/issues/3461 then we can cleanup the cache when a meter is removed and/or configuration changes.

**Comment by tsegismont** [comment]
Closed by #200
