### ISSUE TITLE
Memory usage for http server gauges

### ISSUE THREAD

**Issue by encodeering** [vert-x3/vertx-micrometer-metrics#86]
Hey,

thanks for bridging micrometer with vertx. We are currently seeing some sort of slow memory increase for gauges, especially for the ones from the http server.

It seems that this topic had been addressed in https://github.com/vert-x3/vertx-micrometer-metrics/issues/27

Was there a specific reason why the Gauges still keep a reference in contrast to the other metrics that have been changed with https://github.com/vert-x3/vertx-micrometer-metrics/pull/28?
https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/meters/Gauges.java#L40

Micrometer seems to use all labels, regardless of additional meter filter, as part of the ID. 
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/Gauge.java#L190

We have a filter to remove `LOCAL` and `REMOTE`, but it doesn't seem to be applied to that point in time, which could explain why we see around 250k gauges in a heap dump for just a couple of hours, but not in the metrics sheet from Prometheus for instance.

Application is running on Vertx `3.8.1`

**Comment by vietj** [comment]
can you investigate @jotak ?

**Comment by encodeering** [comment]
Wrote a small sample and my previous statement with the ID's seems to be wrong. 
ID will be just the name without `LOCAL` and `REMOTE` with the `ignoreTags` filter.

Will also investigate further, but this is what I used, maybe you have some tips for me:

```
fun main () {
    val latch = CountDownLatch (1)

    println ("starting")

    val registry = SimpleMeterRegistry ().apply {
        config ().meterFilter (ignoreTags (
            Label.LOCAL.toString (),
            Label.REMOTE.toString ()
        ))
    }

    val factory = usingVertx (registry)

    for (i in 1..10000000) {
        factory (arrayOf ("${random ()}", "${random ()}"))
    }

    println ("waiting")

    latch.await ()
}

fun usingVertx (registry: MeterRegistry): (Array<String>) -> LongAdder
    = Gauges ("name", "description", Supplier (::LongAdder), ToDoubleFunction<LongAdder> (LongAdder::toDouble), registry, Label.LOCAL, Label.REMOTE)::get

fun usingMicrometer  (registry: MeterRegistry): (Array<String>) -> LongAdder = {
    val t = LongAdder ()

    Gauge.builder ("name", t, ToDoubleFunction<LongAdder> (LongAdder::toDouble))
         .description ("description")
         .tags (Labels.toTags (arrayOf (Label.LOCAL, Label.REMOTE), it))
         .register (registry)

    t
}
```

**Comment by encodeering** [comment]
The issue seems to arise when a composite registry is in between, which doesn't have the meter filters applied to it. In that case, the final `MeterId` instance will contain all tags.

Sorry for taking your time. Not sure if you still want to look at the extra storage inside of the gauge, but going to ask micrometer if there is a way without applying all filters the outer-most registry again.

Alternatively it may be an option to choose the wanted labels upfront during the creation of `VertxHttpServerMetrics` or other bridges to remove extra dimensions.

**Comment by jotak** [comment]
Hi @encodeering ,

Sorry I haven't had time to investigate yet, will do so. Trying to understand: so the micrometer's composite registry is storing gauge ids (with labels) regardless what is filtered or not - and so, beside a potential fix in micrometer, we could also do something here to filter out unwanted labels _before_ providing it to micrometer.

Maybe the first thing to try could be to check if this is already fixed in new versions of micrometer in which case we should upgrade.

If I remember correctly the main reason why we don't filter labels beforehand is to keep it simpler and not duplicate the filtering mechanism as micrometer already does it... assuming it does it well.

**Comment by encodeering** [comment]
Hi @jotak,

no worries about that.

Here a bit of the context: We are using a composite registry as aggregation repository for `any` other registry that may want to take part getting the metrics and this details should not be known by any client. All `removal` filters will now be applied to the outer-most composite registry - so it's not an urgent topic. 

Changing different metrics per filter works without a problem. For instance, a filter to activate distribution information per (registered) registry, as you suggest in the [advanced usage](https://vertx.io/docs/vertx-micrometer-metrics/java/#_advanced_usage) section, can be added to any of these.

I am not aware of the implementation, but it might have consequences if micrometer applies the union of all filters to the parental composite, given this structure.

```
Composite (A)
    |
    ---- JMX (B) | without PATH
    |
    ---- Prometheus (C) | without PATH, CODE, LOCAL
```

Anyhow, might be worth checking if micrometer supports this in a newer version as you said, even though it still might be beneficial to start with less (zero) labels:

* easier to add new repository types if the bridge starts with a composite by default, or can be one default
* performance might be better because unwanted labels do not have to be removed
* default labels could still be anything that is set up right now to preserve compatibility
* using additivity only could also make things more homogeneous

**Comment by jonatan-ivanov** [comment]
I have the same issue: the `Meter.Id` contains the tags and one of the tags is the path that frequently contains resource ids in case of REST services.

Does anyone know why wasn't the `ConcurrentHashMap` removed from `Gauges` while it was removed from everywhere else in #28 ? Also, why was it needed in the first place?

**Comment by jotak** [comment]
@jonatan-ivanov iirc the difference of implementation between gauges and others was for historical reasons, as micrometer api didn't offer strong references on gauges, so I had to keep references in another way. But see point number 2 here: https://github.com/vert-x3/vertx-micrometer-metrics/issues/62 : since mm 1.1 we can have strong reference on gauges so this difference with counters and such is now probably obsolete. If you have some time for that, a PR is welcome , else I'll work on that as soon as I can.

**Comment by jonatan-ivanov** [comment]
@jotak I see, I did not know about this [property](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing) of gauges, thank you for your answer.

I think we are talking about two things here, I'm happy to help and open PRs for both:
1. Prettifying the codebase by removing the `ConcurrentHashMap` and using the built-in [`strongReference`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-test/src/main/java/io/micrometer/core/tck/GaugeTest.java#L86) feature.
2. As far as I understand, fixing this will not fix the memory leak, right?

Since one of the tags is the path, which can vary a lot (e.g.: resourceId), and since gauges with different tags (values) are different, not the `ConcurrentHashMap` but the micrometer registry will hold the reference for an enormous amount of gauges, right?

**Comment by jotak** [comment]
@jonatan-ivanov it's still possible to run into memory issues indeed when some tags value are unbounded and high cardinality, there will be no magic against that. So in such situation it's recommended to disable or amend the 'faulty' labels, such as Path. This topic is documented here: https://vertx.io/docs/vertx-micrometer-metrics/java/#_labels_and_matchers

But with gauges it's a bit worse if I remember correctly, as references are kept by Vert.x in a map _before_ labels are eventually filtered out which would mean that disabling labels would have no effect over the memory consumption of this map. I would need to double-check the code but I'm pretty sure it's what is happening, and that's why getting rid of this map would be good.

**Comment by jotak** [comment]
Actually it turns out I was wrong, the concurrent hashmap we use here is bound to the labels cardinality _after_ applying the filters so it shouldn't grow more than the actual micrometer registry. And btw getting rid of that map doesn't seem _that_ easy

**Comment by jotak** [comment]
(Here's a test proving that: )

```java
  @Test
  public void testGaugesMapMemory() {
    MeterRegistry registry = new SimpleMeterRegistry();
    Gauges<LongAdder> g1 = new Gauges<>("my_gauge", "", LongAdder::new, LongAdder::doubleValue, registry, Label.EB_ADDRESS);
    g1.get("1").increment();
    g1.get("2").increment();
    g1.get("3").increment();
    g1.get("4").increment();
    g1.get("5").increment();

    assertThat(g1.gauges.size()).isEqualTo(5);

    BackendRegistries.registerMatchers(registry, ALL_LABELS, Collections.singletonList(new Match()
      .setLabel("address")
      .setType(MatchType.REGEX)
      .setValue(".*")
      .setAlias("_")));

    Gauges<LongAdder> g2 = new Gauges<>("my_gauge_2", "", LongAdder::new, LongAdder::doubleValue, registry, Label.EB_ADDRESS);
    g2.get("1").increment();
    g2.get("2").increment();
    g2.get("3").increment();
    g2.get("4").increment();
    g2.get("5").increment();

    assertThat(g2.gauges.size()).isEqualTo(1);
  }
```

**Comment by encodeering** [comment]
Would agree that this is more an issue regarding the variability of all the dimensions that are taken into account by default.

For instance, `PATH` and `CODE` solely are also quite heavy in terms of their cross product and response times are a good candidate for calculating histograms, adding a hidden third dimension when applying a distributional filter in addition. There is more to read about this topic when it comes to [apdex](https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0) calculation.

Might it be an option to start with zero dimension and a configuration that adds wanted labels instead? The default configuration could be all to preserve compatibility.

**Comment by jonatan-ivanov** [comment]
@encodeering I'm not sure about code `CODE`. That set is finite and I would not say it is big while the `PATH` is practically infinite. `CODE` makes it even worse but filtering it out will not solve the issue, `PATH` is still infinite.

@jotak What do you think, is it possible to use the `ROUTE` instead of the `PATH`?

**Comment by jotak** [comment]
If i'm correct, only bounded-cardinality labels are currently enabled by default. See here: `PATH` labels is not enabled by default so you have to manually turn it on.

@jonatan-ivanov if I understand correctly what you want, you'd like to re-use the route pattern definition as provided to vertx-web / Router as a label instead of the actual path, right? (e.g. `/resource/:id` instead of `/resource/123465`) That would be nice indeed, but it has implications in other vertx modules as this information is currently not accessible to the Metrics SPI (it was also discussed here : https://github.com/vert-x3/vertx-micrometer-metrics/issues/34 ). Unfortunately at the moment I'm lacking time to do that :-( So any help would be appreciated

In the meantime, you have a solution although it involves more work on your side, using regex and filters you can map the path back from `/resource/123465` to `/resource/:id`:

```java
    MeterRegistry registry = BackendRegistries.getDefaultNow();

    registry.config().meterFilter(MeterFilter.replaceTagValues("path", path -> {
      // do some regex matching
      return modifiedPath;
    }));
```

**Comment by jotak** [comment]
Actually I've just seen it mentioned here: https://github.com/vert-x3/vertx-web/issues/1431
