### ISSUE TITLE
Missing metrics for vertx.http.server with Prometheus

### ISSUE THREAD

**Issue by elR1co** [vert-x3/vertx-micrometer-metrics#87]
I am using the vertx micrometer library with Prometheus as backend registry on a vertx HTTP server. When I display the available metrics, I am missing the `vertx.http.server.*` ones by default. Only when a first client do an HTTP request, then I get the metrics.

Would it be possible to get these `vertx.http.server.*` metrics with a default value as soon as the server is up, and not wait for the first request ?

Thanks by advance.

**Comment by jotak** [comment]
The problem is that these metrics have dimensions, that is they only exist for a given set of labels such as the http verb, response code, potentially the remote end, etc. So what you ask would be to initialize the metrics across ALL these dimensions, which is not possible because the label values are not always known.

But I would ask, why would you need that? Maybe there's other ways to work around your issue?

**Comment by elR1co** [comment]
Ok, let's be specific. Let's say I have an HTTP server and I want to know the number of users connected with websockets. Before the first user is doing a request, the metric does not exist. For Prometheus, it is like the server is down as we have a "hole" in our timeseries. A workaround would be to trigger a health check at the server startup of course. But does it make sense to you to give a default value of 0 at startup for this metric for example ?
